name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          path: kansei_interfaces

      - name: Add nightly Debian repository and rosdep sources list
        run: |
          sudo apt update && sudo apt install curl
          curl -s ${{ secrets.SERVER_BASE_URL }}/debian/setup-nightly.bash | bash -s
          curl -s ${{ secrets.SERVER_BASE_URL }}/rosdep/setup.bash | bash -s

      - name: Build and test workspace
        uses: ichiro-its/ros2-build-and-test-action@main
        with:
          ros2-distro: rolling
