name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          path: kansei_interfaces

      - name: Build and test workspace
        uses: ichiro-its/ros2-build-and-test-action@main
        with:
          ros2-distro: rolling
